uploads = []
generated = []

[[outputs]]
id = "g1QAotLkAzOjZSXSGlGwj"
uri = "file://chouiaar-travel-agency.tar.gz"
type = "unspecified"
title = "جميع ملفات الموقع — chouiaar-travel-agency.tar.gz (96 MB)"

[[outputs]]
id = "y36MB_OCW_hYOSVbNqDxq"
uri = "file://finel_project_chouiaartravel.zip"
type = "unspecified"
title = "finel project chouiaartravel.zip"
