uploads = []
generated = []

[[outputs]]
id = "g1QAotLkAzOjZSXSGlGwj"
uri = "file://chouiaar-travel-agency.tar.gz"
type = "unspecified"
title = "جميع ملفات الموقع — chouiaar-travel-agency.tar.gz (96 MB)"

[[outputs]]
id = "y36MB_OCW_hYOSVbNqDxq"
uri = "file://finel_project_chouiaartravel.zip"
type = "unspecified"
title = "finel project chouiaartravel.zip"

[[outputs]]
id = "Hd0-70L6AovQuWEFJ0jI-"
uri = "file://CHOUIAAR_TRAVEL_AGENCY_PROJECT.zip"
type = "unspecified"
title = "CHOUIAAR TRAVEL AGENCY — VPS Package (3.37 MB)"

[[outputs]]
id = "Ys1yuSmhKkYKsIEW-m-VL"
uri = "file://chouiaar_vps.zip"
type = "unspecified"
title = "chouiaar_vps.zip — PORT 8084"
